# Stage 1: Build frontend
FROM node:18 AS frontend-builder
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .
RUN npm run build

# Stage 2: Runtime image
FROM node:18 AS final
WORKDIR /app/frontend
COPY --from=frontend-builder /app/frontend /app/frontend

ENV NEXT_PUBLIC_BACKEND_ROOT_URL=${NEXT_PUBLIC_BACKEND_ROOT_URL}
ENV NEXT_PUBLIC_FRONTEND_ROOT_URL=${NEXT_PUBLIC_FRONTEND_ROOT_URL}


RUN npm install --omit=dev
EXPOSE 3000

CMD ["npm", "start"]