name: CD Template

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Azure Web App (Docker)
      run: |
        az webapp config container set \
          --name ${{ secrets.DEV_WEB_APP_NAME }} \
          --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} \
          --docker-custom-image-name ${{ secrets.ACR_NAME }}.azurecr.io/tripplanner:latest \
          --docker-registry-server-url https://${{ secrets.ACR_NAME }}.azurecr.io

    - name: Restart Azure Web App
      run: |
        az webapp restart --name ${{ secrets.DEV_WEB_APP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP_NAME }}
