name: Build and Deploy Workflow

on:
  push:
    branches:
      - feature/cicd
  workflow_dispatch:

jobs:
  ci:
    name: Continuous Integration
    uses: ./.github/workflows/ci-template.yml

  cd:
    name: Continuous Deployment
    needs: ci
    uses: ./.github/workflows/cd-template.yml
    secrets: inherit
