name: Build and Deploy Workflow

on:
  push:
    branches:
      - feature/cicd
  workflow_dispatch:

jobs:
  ci:
    name: Build
    uses: ./.github/workflows/ci-template.yml
    secrets: inherit

  cd:
    name: Deploy
    needs: ci
    uses: ./.github/workflows/cd-template.yml
    secrets: inherit
