name: Build and Deploy Workflow

on:
  push:
    branches:
      - feature/cicd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          }

    - name: Log in to ACR
      run: |
        az acr login --name <your-acr-name>

    - name: Build and Push Docker Image
      run: |
        docker build -t <your-acr-name>.azurecr.io/myapp:latest .
        docker push <your-acr-name>.azurecr.io/myapp:latest

    - name: Deploy to Azure Container Apps
      run: |
        az containerapp update \
          --name myapp \
          --resource-group <your-resource-group> \
          --image <your-acr-name>.azurecr.io/myapp:latest
