name: '[FE] Build and Deploy Workflow'

on:
  push:
    branches:
      # - feature/cicd
      - release-fe
  workflow_dispatch:
    inputs:
      BuildNumber:
        description: 'Build number to deploy (e.g., latest or a specific tag). Default is GitHub build number.'
        required: false
        default: 'latest'

jobs:
  ci:
    name: Build
    uses: ./.github/workflows/fe-ci-template.yml
    secrets: inherit

  cd:
    name: Deploy
    needs: ci
    uses: ./.github/workflows/fe-cd-template.yml
    with:
      BuildNumber: ${{ github.event.inputs.BuildNumber || github.run_number || 'latest' }} 
    secrets: inherit
