name: '[BE] Build and Deploy Workflow'

on:
  push:
    branches:
      - feature/cicd
      - release-be
  workflow_dispatch:
    inputs:
      BuildNumber:
        description: 'Build number to deploy (e.g., latest or a specific tag). Default is GitHub build number.'
        required: false
        default: 'latest'
      Environment:
        description: 'Deployment environment (dev, prod)'
        required: false
        default: 'dev'

jobs:
  ci:
    name: Build
    uses: ./.github/workflows/be-ci-template.yml
    with:
      BuildNumber: ${{ github.event.inputs.BuildNumber || github.run_number || 'latest' }}
      Environment: ${{ github.event.inputs.Environment || 'dev' }}
    secrets: inherit

  cd:
    name: Deploy
    needs: ci
    uses: ./.github/workflows/be-cd-template.yml
    with:
      BuildNumber: ${{ github.event.inputs.BuildNumber || github.run_number || 'latest' }}
      Environment: ${{ github.event.inputs.Environment || 'dev' }} 
    secrets: inherit
