name: '[FE] Deploy workflow'

on:
  push:
    branches:
    # - feature/cicd
    - release-fe-dev-cd
  workflow_dispatch:
    inputs:
      buildNumber:
        type: string
        description: 'Build number to deploy (e.g., latest or a specific tag)'
        required: false
        default: 'latest'
      envCode:
        type: string
        description: 'Deployment environment (dev, prod)'
        required: false
        default: 'dev'

jobs:
  cd:
    name: Deploy
    uses: ./.github/workflows/template-cd-fe.yml
    with:
      buildNumber: ${{ github.event.inputs.buildNumber || 'latest' }} 
      envCode: ${{ github.event.inputs.envCode || 'dev' }}
    secrets: inherit
