name: '[FE] CD Template'

on:
  workflow_call:
    inputs:
      buildNumber:
        required: false
        type: string
        default: 'latest'
      envCode:
        required: false
        type: string
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.envCode }}

    steps:

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          }

    - name: Log in to ACR
      run: |
        az acr login --name ${{ vars.ACR_NAME }}

    - name: Deploy to Azure Web App (Docker)
      run: |
        az webapp config container set \
          --name ${{ vars.WEB_APP_FE_NAME }} \
          --resource-group ${{ vars.RESOURCE_GROUP_NAME }} \
          --container-image-name ${{ vars.ACR_NAME }}.azurecr.io/tripplanner/fe:${{ inputs.buildNumber }} \
          --container-registry-url https://${{ vars.ACR_NAME }}.azurecr.io

    - name: Restart Azure Web App
      run: |
        az webapp restart --name ${{ vars.WEB_APP_FE_NAME }} \
          --resource-group ${{ secrets.RESOURCE_GROUP_NAME }}
