name: '[FE] CI Template'

on:
  workflow_call:
    inputs:
      buildNumber:
        required: false
        type: string
        default: 'latest'
      envCode:
        required: false
        type: string
        default: 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.envCode }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          }

    - name: Log in to ACR
      run: |
        az acr login --name ${{ vars.ACR_NAME }}

    - name: Build and Push Frontend Docker Image
      run: |
        BUILD_NUMBER=${{ github.run_number }}
        
        docker build -t ${{ vars.ACR_NAME }}.azurecr.io/tripplanner/fe:latest \
                      -t ${{ vars.ACR_NAME }}.azurecr.io/tripplanner/fe:${{ inputs.buildNumber }} \
                      --build-arg BUILD_NUMBER=${{ inputs.buildNumber }} \
                      --build-arg ENV_CODE=${{ inputs.envCode }} \
                      --build-arg NEXT_PUBLIC_FRONTEND_ROOT_URL=https://your-frontend.com \
                      -f Dockerfile.fe .

        docker push ${{ vars.ACR_NAME }}.azurecr.io/tripplanner/fe:latest
        docker push ${{ vars.ACR_NAME }}.azurecr.io/tripplanner/fe:$BUILD_NUMBER
