name: CI

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          }

    - name: Log in to ACR
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build and Push Frontend Docker Image
      run: |
        BUILD_NUMBER=${{ github.run_number }}

        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/tripplanner/fe:latest \
                      -t ${{ secrets.ACR_NAME }}.azurecr.io/tripplanner/fe:$BUILD_NUMBER \
                      --build-arg NEXT_PUBLIC_FRONTEND_ROOT_URL=https://your-frontend.com \
                      -f Dockerfile.fe .

        docker push ${{ secrets.ACR_NAME }}.azurecr.io/tripplanner/fe:latest
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/tripplanner/fe:$BUILD_NUMBER
